repos:
-   repo: local
    hooks:
      - id: flake8
        name: "Style check using flake8"
        entry: flake8 .
        language: system
        types: [python]
      - id: black
        name: "Style check using black"
        entry: black --check .
        language: system
        types: [python]
      - id: isort
        name: "Check import order with isort"
        entry: isort --check .
        language: system
        types: [python]
      - id: pylint
        name: "Static checking with pylint"
        entry: pylint --recursive=y .
        language: system
        types: [python]